apiVersion: workflow.marketplace.example.com/v1alpha1
kind: MarketplaceWorkflow
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: marketplaceworkflow-sample
spec:
  # TODO(user): Add fields here
