FROM golang:1.26.5-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux \
    go build \
    -o /out/publishing-service \
    ./cmd/publishing-service


FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder \
    /out/publishing-service \
    /publishing-service

ENTRYPOINT ["/publishing-service"]