apiVersion: v1
kind: Service

metadata:
  name: marketplace-status-controller
  namespace: marketplace-system

  labels:
    app: marketplace-status-controller

    monitoring: marketplace

spec:

  selector:
    app: marketplace-status-controller

  ports:

    - name: metrics
      port: 9090
      targetPort: 9090