//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceWorkflow) DeepCopyInto(out *MarketplaceWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceWorkflow.
func (in *MarketplaceWorkflow) DeepCopy() *MarketplaceWorkflow {
	if in == nil {
		return nil
	}
	out := new(MarketplaceWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketplaceWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceWorkflowList) DeepCopyInto(out *MarketplaceWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MarketplaceWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceWorkflowList.
func (in *MarketplaceWorkflowList) DeepCopy() *MarketplaceWorkflowList {
	if in == nil {
		return nil
	}
	out := new(MarketplaceWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketplaceWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceWorkflowSpec) DeepCopyInto(out *MarketplaceWorkflowSpec) {
	*out = *in
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.WorkflowTemplateRef = in.WorkflowTemplateRef
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]WorkflowParameter, len(*in))
		copy(*out, *in)
	}
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SuccessfulRunsHistoryLimit != nil {
		in, out := &in.SuccessfulRunsHistoryLimit, &out.SuccessfulRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedRunsHistoryLimit != nil {
		in, out := &in.FailedRunsHistoryLimit, &out.FailedRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceWorkflowSpec.
func (in *MarketplaceWorkflowSpec) DeepCopy() *MarketplaceWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(MarketplaceWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceWorkflowStatus) DeepCopyInto(out *MarketplaceWorkflowStatus) {
	*out = *in
	if in.LastScheduledTime != nil {
		in, out := &in.LastScheduledTime, &out.LastScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceWorkflowStatus.
func (in *MarketplaceWorkflowStatus) DeepCopy() *MarketplaceWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(MarketplaceWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowParameter) DeepCopyInto(out *WorkflowParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowParameter.
func (in *WorkflowParameter) DeepCopy() *WorkflowParameter {
	if in == nil {
		return nil
	}
	out := new(WorkflowParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowTemplateReference) DeepCopyInto(out *WorkflowTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowTemplateReference.
func (in *WorkflowTemplateReference) DeepCopy() *WorkflowTemplateReference {
	if in == nil {
		return nil
	}
	out := new(WorkflowTemplateReference)
	in.DeepCopyInto(out)
	return out
}
