// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/publishing.proto

package publishingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketplacePublishingService_UpdateJobStatus_FullMethodName = "/marketplace.publishing.v1.MarketplacePublishingService/UpdateJobStatus"
)

// MarketplacePublishingServiceClient is the client API for MarketplacePublishingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketplacePublishingServiceClient interface {
	UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error)
}

type marketplacePublishingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplacePublishingServiceClient(cc grpc.ClientConnInterface) MarketplacePublishingServiceClient {
	return &marketplacePublishingServiceClient{cc}
}

func (c *marketplacePublishingServiceClient) UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobStatusResponse)
	err := c.cc.Invoke(ctx, MarketplacePublishingService_UpdateJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplacePublishingServiceServer is the server API for MarketplacePublishingService service.
// All implementations must embed UnimplementedMarketplacePublishingServiceServer
// for forward compatibility.
type MarketplacePublishingServiceServer interface {
	UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error)
	mustEmbedUnimplementedMarketplacePublishingServiceServer()
}

// UnimplementedMarketplacePublishingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketplacePublishingServiceServer struct{}

func (UnimplementedMarketplacePublishingServiceServer) UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJobStatus not implemented")
}
func (UnimplementedMarketplacePublishingServiceServer) mustEmbedUnimplementedMarketplacePublishingServiceServer() {
}
func (UnimplementedMarketplacePublishingServiceServer) testEmbeddedByValue() {}

// UnsafeMarketplacePublishingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketplacePublishingServiceServer will
// result in compilation errors.
type UnsafeMarketplacePublishingServiceServer interface {
	mustEmbedUnimplementedMarketplacePublishingServiceServer()
}

func RegisterMarketplacePublishingServiceServer(s grpc.ServiceRegistrar, srv MarketplacePublishingServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketplacePublishingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketplacePublishingService_ServiceDesc, srv)
}

func _MarketplacePublishingService_UpdateJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplacePublishingServiceServer).UpdateJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplacePublishingService_UpdateJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplacePublishingServiceServer).UpdateJobStatus(ctx, req.(*UpdateJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketplacePublishingService_ServiceDesc is the grpc.ServiceDesc for MarketplacePublishingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketplacePublishingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.publishing.v1.MarketplacePublishingService",
	HandlerType: (*MarketplacePublishingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateJobStatus",
			Handler:    _MarketplacePublishingService_UpdateJobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/publishing.proto",
}
