// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/publishing.proto

package publishingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobPhase int32

const (
	JobPhase_JOB_PHASE_UNSPECIFIED JobPhase = 0
	JobPhase_JOB_PHASE_PENDING     JobPhase = 1
	JobPhase_JOB_PHASE_RUNNING     JobPhase = 2
	JobPhase_JOB_PHASE_SUCCEEDED   JobPhase = 3
	JobPhase_JOB_PHASE_FAILED      JobPhase = 4
	JobPhase_JOB_PHASE_ERROR       JobPhase = 5
	JobPhase_JOB_PHASE_SKIPPED     JobPhase = 6
	JobPhase_JOB_PHASE_OMITTED     JobPhase = 7
)

// Enum value maps for JobPhase.
var (
	JobPhase_name = map[int32]string{
		0: "JOB_PHASE_UNSPECIFIED",
		1: "JOB_PHASE_PENDING",
		2: "JOB_PHASE_RUNNING",
		3: "JOB_PHASE_SUCCEEDED",
		4: "JOB_PHASE_FAILED",
		5: "JOB_PHASE_ERROR",
		6: "JOB_PHASE_SKIPPED",
		7: "JOB_PHASE_OMITTED",
	}
	JobPhase_value = map[string]int32{
		"JOB_PHASE_UNSPECIFIED": 0,
		"JOB_PHASE_PENDING":     1,
		"JOB_PHASE_RUNNING":     2,
		"JOB_PHASE_SUCCEEDED":   3,
		"JOB_PHASE_FAILED":      4,
		"JOB_PHASE_ERROR":       5,
		"JOB_PHASE_SKIPPED":     6,
		"JOB_PHASE_OMITTED":     7,
	}
)

func (x JobPhase) Enum() *JobPhase {
	p := new(JobPhase)
	*p = x
	return p
}

func (x JobPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_api_publishing_proto_enumTypes[0].Descriptor()
}

func (JobPhase) Type() protoreflect.EnumType {
	return &file_api_publishing_proto_enumTypes[0]
}

func (x JobPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobPhase.Descriptor instead.
func (JobPhase) EnumDescriptor() ([]byte, []int) {
	return file_api_publishing_proto_rawDescGZIP(), []int{0}
}

type UpdateJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobStatus             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusRequest) Reset() {
	*x = UpdateJobStatusRequest{}
	mi := &file_api_publishing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusRequest) ProtoMessage() {}

func (x *UpdateJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_publishing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_publishing_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateJobStatusRequest) GetJob() *JobStatus {
	if x != nil {
		return x.Job
	}
	return nil
}

type UpdateJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusResponse) Reset() {
	*x = UpdateJobStatusResponse{}
	mi := &file_api_publishing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusResponse) ProtoMessage() {}

func (x *UpdateJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_publishing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_publishing_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateJobStatusResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type JobStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowUid     string                 `protobuf:"bytes,1,opt,name=workflow_uid,json=workflowUid,proto3" json:"workflow_uid,omitempty"`
	WorkflowName    string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Phase           JobPhase               `protobuf:"varint,5,opt,name=phase,proto3,enum=marketplace.publishing.v1.JobPhase" json:"phase,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Steps           []*StepStatus          `protobuf:"bytes,9,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_api_publishing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_publishing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_api_publishing_proto_rawDescGZIP(), []int{2}
}

func (x *JobStatus) GetWorkflowUid() string {
	if x != nil {
		return x.WorkflowUid
	}
	return ""
}

func (x *JobStatus) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *JobStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *JobStatus) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *JobStatus) GetPhase() JobPhase {
	if x != nil {
		return x.Phase
	}
	return JobPhase_JOB_PHASE_UNSPECIFIED
}

func (x *JobStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *JobStatus) GetSteps() []*StepStatus {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phase         JobPhase               `protobuf:"varint,3,opt,name=phase,proto3,enum=marketplace.publishing.v1.JobPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_api_publishing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_publishing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_api_publishing_proto_rawDescGZIP(), []int{3}
}

func (x *StepStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StepStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepStatus) GetPhase() JobPhase {
	if x != nil {
		return x.Phase
	}
	return JobPhase_JOB_PHASE_UNSPECIFIED
}

func (x *StepStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StepStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *StepStatus) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

var File_api_publishing_proto protoreflect.FileDescriptor

const file_api_publishing_proto_rawDesc = "" +
	"\n" +
	"\x14api/publishing.proto\x12\x19marketplace.publishing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x16UpdateJobStatusRequest\x126\n" +
	"\x03job\x18\x01 \x01(\v2$.marketplace.publishing.v1.JobStatusR\x03job\"3\n" +
	"\x17UpdateJobStatusResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"\xa6\x03\n" +
	"\tJobStatus\x12!\n" +
	"\fworkflow_uid\x18\x01 \x01(\tR\vworkflowUid\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12)\n" +
	"\x10resource_version\x18\x04 \x01(\tR\x0fresourceVersion\x129\n" +
	"\x05phase\x18\x05 \x01(\x0e2#.marketplace.publishing.v1.JobPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12;\n" +
	"\x05steps\x18\t \x03(\v2%.marketplace.publishing.v1.StepStatusR\x05steps\"\xa2\x02\n" +
	"\n" +
	"StepStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\x05phase\x18\x03 \x01(\x0e2#.marketplace.publishing.v1.JobPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts*\xc5\x01\n" +
	"\bJobPhase\x12\x19\n" +
	"\x15JOB_PHASE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_PHASE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_PHASE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_PHASE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10JOB_PHASE_FAILED\x10\x04\x12\x13\n" +
	"\x0fJOB_PHASE_ERROR\x10\x05\x12\x15\n" +
	"\x11JOB_PHASE_SKIPPED\x10\x06\x12\x15\n" +
	"\x11JOB_PHASE_OMITTED\x10\a2\x98\x01\n" +
	"\x1cMarketplacePublishingService\x12x\n" +
	"\x0fUpdateJobStatus\x121.marketplace.publishing.v1.UpdateJobStatusRequest\x1a2.marketplace.publishing.v1.UpdateJobStatusResponseBbZ`github.com/dipen1510/marketplace-workflow-platform/publishing-status-controller/api;publishingv1b\x06proto3"

var (
	file_api_publishing_proto_rawDescOnce sync.Once
	file_api_publishing_proto_rawDescData []byte
)

func file_api_publishing_proto_rawDescGZIP() []byte {
	file_api_publishing_proto_rawDescOnce.Do(func() {
		file_api_publishing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_publishing_proto_rawDesc), len(file_api_publishing_proto_rawDesc)))
	})
	return file_api_publishing_proto_rawDescData
}

var file_api_publishing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_publishing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_publishing_proto_goTypes = []any{
	(JobPhase)(0),                   // 0: marketplace.publishing.v1.JobPhase
	(*UpdateJobStatusRequest)(nil),  // 1: marketplace.publishing.v1.UpdateJobStatusRequest
	(*UpdateJobStatusResponse)(nil), // 2: marketplace.publishing.v1.UpdateJobStatusResponse
	(*JobStatus)(nil),               // 3: marketplace.publishing.v1.JobStatus
	(*StepStatus)(nil),              // 4: marketplace.publishing.v1.StepStatus
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_api_publishing_proto_depIdxs = []int32{
	3, // 0: marketplace.publishing.v1.UpdateJobStatusRequest.job:type_name -> marketplace.publishing.v1.JobStatus
	0, // 1: marketplace.publishing.v1.JobStatus.phase:type_name -> marketplace.publishing.v1.JobPhase
	5, // 2: marketplace.publishing.v1.JobStatus.started_at:type_name -> google.protobuf.Timestamp
	5, // 3: marketplace.publishing.v1.JobStatus.finished_at:type_name -> google.protobuf.Timestamp
	4, // 4: marketplace.publishing.v1.JobStatus.steps:type_name -> marketplace.publishing.v1.StepStatus
	0, // 5: marketplace.publishing.v1.StepStatus.phase:type_name -> marketplace.publishing.v1.JobPhase
	5, // 6: marketplace.publishing.v1.StepStatus.started_at:type_name -> google.protobuf.Timestamp
	5, // 7: marketplace.publishing.v1.StepStatus.finished_at:type_name -> google.protobuf.Timestamp
	1, // 8: marketplace.publishing.v1.MarketplacePublishingService.UpdateJobStatus:input_type -> marketplace.publishing.v1.UpdateJobStatusRequest
	2, // 9: marketplace.publishing.v1.MarketplacePublishingService.UpdateJobStatus:output_type -> marketplace.publishing.v1.UpdateJobStatusResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_publishing_proto_init() }
func file_api_publishing_proto_init() {
	if File_api_publishing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_publishing_proto_rawDesc), len(file_api_publishing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_publishing_proto_goTypes,
		DependencyIndexes: file_api_publishing_proto_depIdxs,
		EnumInfos:         file_api_publishing_proto_enumTypes,
		MessageInfos:      file_api_publishing_proto_msgTypes,
	}.Build()
	File_api_publishing_proto = out.File
	file_api_publishing_proto_goTypes = nil
	file_api_publishing_proto_depIdxs = nil
}
